import {StyleSheet, Platform} from 'react-native';
import {Colors, Metrics, Fonts} from '../../theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  bg: {backgroundColor: Colors._orange},
  maincontainer: {
    flex: 1,
    backgroundColor: Colors._orange,
    alignItems: 'center',
  },
  logo: {
    width: Metrics.ratio(200),
    height: Metrics.ratio(140),
  },
  loginLogo: {
    marginTop: Metrics.ratio(64),
  },
  loginText: {
    marginTop: Metrics.ratio(20),
    marginBottom: Metrics.ratio(44),
    alignItems: 'center',
    justifyContent: 'center',
  },
  field: {
    width: Metrics.screenWidth - 2 * Metrics.ratio(19),
    height: Metrics.ratio(54),
    color: Colors.platinum,

    // marginBottom: Metrics.ratio(13),
    borderRadius: Metrics.ratio(5),
    borderWidth: Metrics.ratio(1),
    borderColor: Colors.fieldBg,
    flexDirection: 'row',
    backgroundColor: Colors.fieldBg,
  },
  accessoryView: {
    width: Metrics.ratio(50),
    alignItems: 'center',
    justifyContent: 'center',
    height: Metrics.ratio(50),
    backgroundColor: Colors.fieldBg,
    alignSelf: 'center',
  },
  accessoryPhoneView: {
    width: Metrics.ratio(50),
    alignItems: 'center',
    justifyContent: 'center',
    height: Metrics.ratio(50),
    backgroundColor: Colors.fieldBg,
    alignSelf: 'center',
  },

  accessory: {
    width: Metrics.image.small,
    height: Metrics.image.small,
    resizeMode: 'contain',
  },

  fieldPhoneWrapper: {
    flex: 1,
    backgroundColor: Colors.fieldBg,
    alignItems: 'center',
  },

  input: {
    flex: 1,
    color: Colors.primary,
    fontFamily: Fonts.type.AvenirNextMedium,
    fontSize: Fonts.size.sixteen,
    height: Metrics.ratio(40),
    marginLeft: Metrics.ratio(5),
  },
  login: {
    width: Metrics.screenWidth - 2 * Metrics.ratio(19),
    height: Metrics.ratio(42),
    borderColor: Colors.white,
    backgroundColor: Colors.transparent,
    borderWidth: Metrics.ratio(2),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Metrics.ratio(5),
    marginTop: Metrics.ratio(19),
    marginBottom: Metrics.ratio(19),
  },
  serverURLParent: {
    width: Metrics.screenWidth,
    height: Metrics.ratio(30),
    backgroundColor: Colors.transparent,
    alignItems: 'center',
    justifyContent: 'center',
    bottom: 0,
    position: 'absolute',
    right: 0,
    left: 0,
  },
  passField: {
    marginTop: Metrics.ratio(18),
  },
  languageBtnContainer: {
    flexDirection: 'row',
    marginVertical: Metrics.ratio(20),
    marginHorizontal: Metrics.screenWidth * 0.04,
    width: Metrics.screenWidth * 0.45,
    height: Metrics.ratio(30),
    borderWidth: 1,
    borderColor: Colors.platinum,
    borderRadius: Metrics.ratio(5),
    backgroundColor: Colors.lightgray,
    overflow: 'hidden',
    elevation: 4,
    position: 'absolute',
    top: Platform.OS === 'android' ? 0 : Metrics.ratio(20),
    right: 0,
    zIndex: 99,
  },
  usingMobileNumber: {
    marginVertical: Metrics.ratio(10),
    width: Metrics.screenWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  becomeAServiceProvider: {
    marginVertical: Metrics.ratio(10),
    width: Metrics.screenWidth,
    alignItems: 'center',
    justifyContent: 'center',
  },
  becomeAServiceProviderText: {
    textDecorationLine: 'underline',
  },
  serverUrlBox: {
    position: 'absolute',
    right: 0,
    left: 0,
    bottom: 0,
    backgroundColor: 'red',
    height: Metrics.ratio(1),
  },
  countryCode: {
    justifyContent: 'center',
    alignItems: 'center',
    height: Metrics.ratio(40),
    paddingHorizontal: Metrics.ratio(6),
  },
  serverChaageBtn: {
    position: 'absolute',
    left: 0,
    bottom: 0,
    width: Metrics.ratio(44),
    height: Metrics.ratio(44),
  },
});
